version: '3.8'

services:
  mysql_srv:
    image: mysql:8.0.32
    container_name: mysql_ctr
    restart: always
    environment:
      MYSQL_DATABASE: job_portal
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: palisha
      MYSQL_PASSWORD: palisha
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql

  phpmyadmin_srv:
    depends_on:
      - mysql_srv
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_ctr
    restart: always
    environment:
      PMA_HOST: mysql_srv
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80

  backend_srv:
    container_name: jobPortal-backend
    restart: unless-stopped
    build:
      context: ./job_portal
      dockerfile: Dockerfile
    depends_on:
      - mysql_srv
    environment:
      MYSQL_HOST: mysql_srv
      MYSQL_USER: palisha
      MYSQL_DATABASE: job_portal
      MYSQL_PASSWORD: palisha
    ports:
      - 5000:5000
    links:
      - mysql_srv:mysql_srv
    volumes:
      - ./job_portal:/opt/backend
  
  frontend_srv:
    container_name: jobportal-frontend
    restart: unless-stopped
    build: 
      context: ./job_portal_frontend
      dockerfile: Dockerfile
    depends_on:
      - backend_srv
    ports:
      - 3000:3000
    volumes:
      - ./job_portal_frontend:/opt/frontend


